language: node_js
node_js: 8
script:
  - npm run build
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
env:
  global:
    # CHROME_CLIENT_ID
    - secure: fRbL4duBfGefst9/zDcECRagn7i/AJRCm3E7zUHSDXdTaMbsAtnC0gZU8VXSls+oB1vUF0WhgqozEp2ziKZwwx6738olDuy8+J/MuXPnpuo5qMW7jTjaw3cgJ0IcOtS9JfEp7cQteMqR+n5ERaQR1OLwidRzY3wbjrJzJbslIBpfwEJSMAGAQNE7xyxx6/04FBflleaC8TcxJtsR4l2fo4OT+53vGwDKUQqHs8Wk9W/d8C5W5svPLeZQ8RXdg9aZhfqr6RxhXl4ZczokleeZ7jDAxEyEw3UYH/Rh7LoEyZLbRQFd3sMxMFPnZ6BFNN/n043bSzBFsXmcCtjjUJEyyxetaqrjTb16092ynXYigkA1DQvhvTdYQ8kwCat+xQlkuRalQTk8rfpIy//ehcFcTqfwg5scuXlZdP3aYYmir3NGkqakeMaAtwS4weV+QoLUVA0mGD6tQLu8djTXu5ni4j4lq5ofEQJCnuGZExi5DZdW2woEpOP5mlM2h+CCJgW12JtAm8ghY5TUSIID8MRd0ZgjWc3dhmFkdbKAK48A+9xHJe6UMnO9dVK1b95FtU7tdzJfhq246UP+CG9VcXOQ1wUKQPU7y77g2NS7mnMqNVAjafWeGCzHWywTSJUsGQbDfmwAKejL9r8UNxqHZZyA0WtWuGw1TzAj0JI2O3A/Mso=
    # CHROME_CLIENT_SECRET
    - secure: kqhpiTHQ/luruDWb/783vGRykD2MHlY9+2N98eFETVM2yRU36wqW7gIGWyKdLtVLcIv3NCedxtusPpBdXYkMC9ffJbEy6X8ut3+5qsnTxQ1etuVRtpA5GY57Xr8+p1aCoNOyZVyClyMcKvQZCfAXzALTqIVSbDFALMCmbds9ZZ1M/cAh6eIMSpGEA3HpNuOVxgqocbeo2ny1l3sEP0SDH/1NwtT06HrkZ8zwik7nG5S11WnZ1rKBdwwZcPLzV3zrGRRt1UyAoVZ3J0BxS04Hqvd9TQHotTz3GcLFEfaD+3+/7ZVKKRwgasXmU8VrJt8Q/GViF2YflOZi4Crgsg7DdGBdaefQ3M4FDCq/+hxB971rIFMkvioTsnavKzQaivyrBm15BazfLX1vSDuqzxRY5ELF6mLimQoptOKiUpkxSj18eVlUe/UqciqUkbaVfGFM6f1QFP36qHubnF2FrPBvgbrczfRaaoNb1ZoBcW2q616UTQcMUibxVKAGt5/BKNpZkEkuugrOEJH0mFzzOiI5Cgh3qw1/YJqxxlpw90VDLqy/ELz2D6k909ccDlBGO9OFjoVmkTrTOdmTe+ZhzYzfi2dvLSlqkDNiLCS2QHR/wJoRjamJAlLWoFxHVQnlejQqLpekNtfGSRY24gFayBIc6olr7E9xiEpVfi6UzRfXpQs=
    # CHROME_REFRESH_TOKEN
    - secure: stD8sHXQn8QS7PS9/Lal1WPQHDAYgH8NmtS1I/ZFEUeXENZccq4JJxjPfBFFCA9Op0s5JvAB5OQXtoHGpuhChIclsIonrh0dNgByGlbIgmfyeDNQn8T3bnYj2UtOvcbDWFJwLj1GamAipV8kpSZ4sgbD1H+FmqhzCvLjXokqeqVPq5eshrenxQHv0QdfWzxW9r0d6/ju+Ns/0doFn7VsWFr1U2oyGVsLXhOHVsUtIXbEPL01yHhpCbK54Gx2mQTJxD0x0jXkEy5YFhHADCnDkv1iRpwH3VSViiA9i812lEPtKvqCxKUHtnWT31njpx8upidWCHDGttzXHyMD7sUNxqJLbkFdEpey20ObjzMDkAS0QfM13vz/+llx0E+Wmlprwv2xqG1nfRLzcxN/fSZiXpamPfK2dai4dEmw6NmEsbck5JcC0kz23weyMwIg6kNGE9JOZF/057j/P+6IQzpTFV56QL9NDCAhBw6Tp5f1Dslm//gHIr4jwp3ZuLeYFvUAbmQ6CdPP/YHo+1kmlVGzUtudDveSlKJe/6+7HrDTWezUdgBwG5wicVVFLsKH2pnK1mLyQ2sSXZPXwcox4yDn7KzbrAlavFv59CJ8R7U6lFWEqjp213w51CEWm5i8zt6hcn9aI99eF/q0IZhdoYNOSkqVEBErzHyKYJVvVBljEcQ=
deploy:
  - provider: releases
    api_key:
      secure: onKtVCr2xIjhMdoZtZP+ay3i5cOZIE+xxUWpYLHr8h9yxIlZQ6+WA6WOjTEmGSWPRnvVWr9tnqcM3iHkrZclvaw2tlzYUO5r7j2zons12oH2wcqSON4fUkEiAgXRcvbdzYpCAdgtrFc02OcwNZmtU7hX+r16uUCV5/O2sfQtz1rBRaIBjxDMoy8Y5tgecoOX0Yai4Ey18zti8hsiuWcut9nA6uc6kBvMB78wQyYVhcgmS8n3V2ENyBYsciJVfpSLCIGZhagUyk/B5iy+a04K3gl/QPj+vRsASNgYDsCVnMC7ZLgCo1hKN6RuGmLA9u3EXGAxbu0CH/kETE8NL/wqQOpaefX6wW5fjxk1PIDusiXLCsK8jV/ZY8VJ0aFt4uKKjLnmS10jTsFmH05WPMmfD76jKjc3nSMmyLGzQBgqP9PyjorDXh6+yaL9nd7Z6cGe/H7NhNis1BR1zOsk1gdJ6rOx0ap++9bnf/3b72unBrkwZ3jfGQ5GWv8ZP7Anhs8lRySjlM69OKauW/EwF8I0ByIR7e3UH/HcxzWOT1rJbWva88srTBObzeP85BUnZyxRveCjF9q12YCM15Y31yI17gDXvaTvzgMIIPShSLPFv5XP9agFYaBTvA8ZI9A4ZIhMv6Uta8Yt2RLgXbhp1fxkePUU3prFBG0TFeamiUfzeXc=
    file: dist/TLD.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
      tags: true
